version: '3'

networks:
  web:
    external: true
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./web:/app:delegated
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PHP_ENABLE_XDEBUG=1
      - PHP_IDE_CONFIG=serverName=KikBotAdminPanel
    ports:
      - '8080:80'
    networks:
      - web
      - default
    depends_on:
      - db
  db:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "yii-db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
#      - ./2. Init Database:/docker-entrypoint-initdb.d
      - ./docker/db/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - default
